### ISSUE TITLE
Tag size definition is misleading for tagStandard, tagCircle, tagCustom

### ISSUE THREAD

**Issue by BenzStefanBosch** [AprilRobotics/apriltag_ros#116]
For AprilTag3 tags (tagStandard, tagCircle, tagCustom) the tag size appears to be defined as the area within the solid black rectangle, leading to misleading size definitions in the tags.yaml.

We observed severe errors in the distance estimation of the markers when using tagStandard41h12 markers, so we investigated the subject further. Looking at the detection images, we noticed that the detection rectangle is drawn on the border of the solid white and solid black square, not around the outermost data bits. This holds true for tagCircle and tagCustom classes as well. For the 'old' tag36h11 the detection size specifies the size of the outer black box, which makes more sense.

IMO the more intuitive measure for "tag size" would be to always use the outermost data bits or black pixels. For the case of tagStandard41h12 there are 9 data bits, the currently implemented tag size refers to the inner 5 bits, leading to an error in depth estimation of 9/5 = 1.8 and this varies depending on the number or data bits per row.

I suspect the reason lies in the workings of the underlying detector and hence would be challenging to change quickly. Once it is known which size to specify, this can easily be corrected when setting up the tags.yaml, but as mentioned it is unintuitive and should at least be defined in the comments of tags.yaml or the documentation.

**Comment by BenzStefanBosch** [comment]
![Detection_size_guide_marked](https://user-images.githubusercontent.com/51699924/153249514-71e76fee-8892-4230-9120-ceb5e5694c21.png)
Here is an overview to visualize the different sizes that need to be specified to get a correct distance estimate.

**Comment by BenzStefanBosch** [comment]
So I stumbled upon the official description for the tag sizes here:
https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation

Still, I think a comment regarding this would be helpful somewhere in the config where you are expected to specify the size.

**Comment by wxmerkt** [comment]
Thank you very much for raising this important point and providing examples. Could you please open a PR to update the README/documentation with the above graphic and description? Many thanks in advance!
