### ISSUE TITLE
parameter camera_frame does not work in new realsease

### ISSUE THREAD

**Issue by robin-shaun** [AprilRobotics/apriltag_ros#123]
Hello, after `apt upgrade apriltag_ros`, I find that parameter `camera_frame` does not work. No matter what I set, the `camera_frame` in tf is always `camera_link`.

**Comment by wxmerkt** [comment]
Hi @robin-shaun 
Following https://github.com/AprilRobotics/apriltag_ros/pull/101, the client uses the frame given in the header of the image message - the parameter `camera_frame` is no longer used

**Comment by robin-shaun** [comment]
Thanks
