### ISSUE TITLE
apriltag_ros not in package list

### ISSUE THREAD

**Issue by joaopsousa99** [AprilRobotics/apriltag_ros#138]
I've installed `apriltag_ros` following the instructions on the `README.md` file, except my ROS distro is noetic. After `catkin build`, I ran `rosdep update`, which I think updates the list of locally installed packages.
When I try to launch the continuous detection node i get
```bash
roslaunch apriltag_ros continuous_detection.launch
RLException: [continuous_detection.launch] is neither a launch file in package [apriltag_ros] nor is [apriltag_ros] a launch file name
The traceback for the exception was written to the log file
```

OS: Ubuntu 20.04
ROS distro: noetic
branch: `master`

**Comment by wxmerkt** [comment]
Have you sourced your workspace after building?
