### ISSUE TITLE
gcc: error: libpython3.9.a: No such file or directory

### ISSUE THREAD

**Issue by aimanalimie** [AprilRobotics/apriltag_ros#142]
Hi, can someone help me regarding this problem. The error occurs during catkin build

![Screenshot from 2022-12-20 02-39-29](https://user-images.githubusercontent.com/102818861/208610469-a912d7ec-b217-4f5f-8446-5447334de4c3.png)

**Comment by wxmerkt** [comment]
This relates to AprilTag and some incorrect configuration of Python - note that 3.9 is not a default version on either 18.04 or 20.04
