### ISSUE TITLE
Extremely High CPU Usage

### ISSUE THREAD

**Issue by davelkan** [AprilRobotics/apriltag_ros#20]
A key advantage of Apriltags 2 over the original is supposedly the substantial savings in CPU. However i'm observing approximately 4x-5x more CPU usage by apriltags2 then by a previous implementation of the original apriltags algorithms (ported to C++) here: https://github.com/swatbotics/apriltags-cpp

**Comment by dmalyuta** [comment]
David, thank you for all the activity! I'll get back to you on all points next month. Just wanted to say so that you don't feel like you're writing into the void.

**Comment by davelkan** [comment]
yep i saw your announcement. There may be a few more PRs from me between now and then :+1: 

thanks for putting this library together. I'm investigating the CPU usage in comparison to the swatbotics apriltags implementation and i'll let you know what i find.

**Comment by davelkan** [comment]
I think the key issue with the CPU is the thresholding. Far too many canidate clusters are created. With better thresholding we may be able to reduce CPU usage dramatically

**Comment by davelkan** [comment]
@dmalyuta 
I've been working on incorporating opencv in order to speed up the code, which includes a partial C++ conversion. Areyou interested in having this merged back?

**Comment by mhkabir** [comment]
@davelkan Would love to test your changes if you pushed them to a branch somewhere! I'm working on switching my old software stack to use AprilTags2, and would be happy to help however I can. :)

**Comment by davelkan** [comment]
I'll work on cleaning them up this week. I've made fairly dramatic changes to get this compatible with my set up. I'll try and get this up by end of week.

**Comment by dmalyuta** [comment]
@davelkan I'm happy for you to push all your work into a separate branch and we can take it from there to eventually merge things with master!

**Comment by skohlbr** [comment]
There's also [discussion on ROS Answers about high observed CPU usage](https://answers.ros.org/question/299115/april-tag-2-ros-pose-detection/). I linked to this issue in the comments.

**Comment by davelkan** [comment]
@dmalyuta sorry for the delay. I've had a bunch of other priority work dumped on my lap and have been sidetracked. I'm in the process of getting my various changes through an internal review and will be pushing it to a branch here as soon as possible

**Comment by rjosodtssp** [comment]
Anyone solve this problem yet ? It really uses too much CPU on my computer

**Comment by wxmerkt** [comment]
Can you please try pull request #43? I think this should fix your issue.
