### ISSUE TITLE
FPS question

### ISSUE THREAD

**Issue by tschmidt64-SC** [AprilRobotics/apriltag_ros#35]
When I run this node, it seems that detection is capped at 1 fps. Is this an artificial constraint? I'm running this on a 8th gen i7 with loads of RAM, so hardware isn't the issue.

**Comment by wxmerkt** [comment]
Can you please try pull request #43? I think this should fix your issue.

**Comment by wxmerkt** [comment]
This should have been made faster by #43. Please note that I am about to _deactivate_ ARM optimisations by default by commenting them out in the `CMakeLists` for a binary release. You can activate them again for your local installation.
