### ISSUE TITLE
missing range check for the function matd_select

### ISSUE THREAD

**Issue by csukuangfj** [AprilRobotics/apriltag_ros#5]
See the code
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/matd.c#L171-L188

Assertions on `r0` and `c0` are not enough to avoid invalid memory acess.

`r1` should be less than `a->rows`
and
`c1` should be less than `a->cols`.

**Comment by wxmerkt** [comment]
Thank you, this since comes from upstream can you please post the issue on https://github.com/aprilrobotics/apriltag?
