### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by npd26** [AprilRobotics/apriltag_ros#50]
Hello,

I am trying to install this package by cloning it in 
catkin_ws/src and using catkin_make
but it is giving me this error,
```
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:578 (message):
  None of the required 'apriltag' found
```
am I missing something to install before this package?

thanks.

**Comment by rgreid** [comment]
@npd26 I added a quickstart to the README.md, you'll find it [here](https://github.com/AprilRobotics/apriltag_ros/tree/rgreid-updated-readme) until the PR is merged.

You need to clone the Apriltag repo also.

**Comment by D-aggie** [comment]
Hello I am still experiencing the same error as the original issue, i tried to follow the link but it is broken, could you please create a new link? Or if there are alternative methods to solve the issue that would work for me too, thank you

**Comment by npd26** [comment]
@D-aggie you need to clone also apriltag package as explained here, [https://github.com/AprilRobotics/apriltag_ros/blob/master/README.md](url)
and also use **catkin_make_isolated**

**Comment by D-aggie** [comment]
thank you
