### ISSUE TITLE
Support of tagStandard41h12

### ISSUE THREAD

**Issue by m0oz** [AprilRobotics/apriltag_ros#53]
In the documentation of [April Tag 3](https://github.com/AprilRobotics/apriltag#usage) it is recommended to use family tagStandard41h12 for all new applications. It would be nice if this family would be supported by this ROS wrapper :)

**Comment by m0oz** [comment]
#54

**Comment by samuelba** [comment]
@m0oz Can you please fix your PR #54 ? Such that it can be merged. Thanks.

**Comment by samuelba** [comment]
This is resolved with this merge ca2e0b959e30c8635304fb2e1c09b411afd9576d
