### ISSUE TITLE
update short description of repository

### ISSUE THREAD

**Issue by v4hn** [AprilRobotics/apriltag_ros#56]
The short description for this repository states

> A ROS wrapper of the AprilTags 2 visual fiducial detector

Please remove the 2 or change it to 3.
The wrong description is confusing when searching for the right repository on github.

**Comment by wxmerkt** [comment]
I don't seem to have the rights to do this edit - @mkrogius, could you please amend? Thank you!

**Comment by mkrogius** [comment]
Done!
