### ISSUE TITLE
The mutex in struct apriltag_detector is initialized but not destroyed

### ISSUE THREAD

**Issue by csukuangfj** [AprilRobotics/apriltag_ros#6]
See the code below

https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/apriltag.c#L366

and

https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/apriltag.c#L382-L391

Although the [documentation][1] does not say that `pthread_mutex_destroy` must be called when the mutex is not needed any longer, it is a good practice to free the resource if it was initialized before.

An example can be found inside `workerpool.c`:

https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/workerpool.c#L114

https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/workerpool.c#L147

[1]: https://linux.die.net/man/3/pthread_mutex_init

**Comment by wxmerkt** [comment]
Thank you, this since comes from upstream can you please post the issue on https://github.com/aprilrobotics/apriltag?
