### ISSUE TITLE
Potential memory leak in the funciton optimize_quad_generic

### ISSUE THREAD

**Issue by csukuangfj** [AprilRobotics/apriltag_ros#7]
See the code
https://github.com/dmalyuta/apriltags2_ros/blob/30629ea495950d961fb093849d021ab811737736/apriltags2/src/apriltag.c#L780-L786

When `quad_update_homographies` returns -1, `this_quad` is never freed.

**Comment by wxmerkt** [comment]
Thank you, this since comes from upstream can you please post the issue on https://github.com/aprilrobotics/apriltag?
