### ISSUE TITLE
image_proc sync problem

### ISSUE THREAD

**Issue by m4xr1sk** [AprilRobotics/apriltag_ros#72]
I'm using image_proc to rectify the image of my camera.
Without image_proc the tag detection works but obvioulsy the orientation is wrongly estimated.

With image_proc the tag detection doesn't work and now I'm getting this warning:

```
[ WARN] [1582182434.473958456]: [image_transport] Topics '/image_proc_fisheye1/image_rect' and '/image_proc_fisheye1/camera_info' do not appear to be synchronized. In the last 10s:
        Image messages received:      301
        CameraInfo messages received: 0
        Synchronized pairs:           0
```

How can I solve?
Is this the problem that tags are not detected any more?

**Comment by parakhm95** [comment]
How are you publishing the camerainfo? Also, is your distortion matrix correct? Because from my experience, things don't work well for fisheye parameters with image_proc. It throws an error about distortion matrix not being available and then quits.

**Comment by wxmerkt** [comment]
Closing due to old age - please reopen if issue still persists
