### ISSUE TITLE
Apriltags in Gazebo

### ISSUE THREAD

**Issue by HappySamuel** [AprilRobotics/apriltag_ros#78]
Hi

Is there any tutorials on implementing apriltag into Gazebo?

Best,
Samuel

**Comment by wxmerkt** [comment]
Hi Samuel,
If should work with (1) simulated cameras and (2) placing objects with the tags as textures in the environment. I am not aware of a tutorial describing both steps but they are likely out there.

Hope you've been able to resolve it.

Best,
Wolfgang

**Comment by shonigmann** [comment]
Hi Samuel,

Its probably a bit late, but I very recently got Apriltag working in Gazebo, so if you have any questions I might be able to help.

Also, if it helps, I made a AR marker cube for gazebo and the corresponding tag config file, which you can find here: https://grabcad.com/library/april-tag-ar-marker-cube-1
