### ISSUE TITLE
Why does this package consume high RAM (6GB for my case)?

### ISSUE THREAD

**Issue by quahyusoon** [AprilRobotics/apriltag_ros#83]
Hi. this package performed quite well except the RAM usage.
After running continuous_detection.launch, the RAM usage shoot up to 6GB on my machine.
Is this considered normal? If yes, why does it consume so much of RAM?
![image](https://user-images.githubusercontent.com/29323307/97656022-5ef36b80-1aa1-11eb-81f3-14b6a9c6d31e.png)

**Comment by wxmerkt** [comment]
Hi @quahyusoon,
Are you using one of the newer, large tag families? This high usage is expected when using tag families that might have tens of thousands of markers.
