### ISSUE TITLE
The topic /tf doesn't publish frame ID "camera" pose.

### ISSUE THREAD

**Issue by Mingchi-Yeh** [AprilRobotics/apriltag_ros#98]
As the title says,the /tf has publish the pose with "camera"->"tag_id" and "camera"->"my_bundle", and the rviz is worked well.

And this is the problem, how can I get the "camera" pose shown in the Figure(red line) , Instead of the my_bundle ("camera"->"my_bundle") pose(orange line).

![1624699047231](https://user-images.githubusercontent.com/54263650/123508665-4fb1d580-d6a3-11eb-86d2-f7d3ba6956a0.jpg)

Thanks.

**Comment by christian-rauch** [comment]
Are you asking for the pose of `camera` in the `my_bundle` frame? In this case you just have to invert the transformation or ask tf to do that for you.

`camera` is the parent frame of your tag. For now, you have to configure the `camera_frame` launchfile argument
https://github.com/AprilRobotics/apriltag_ros/blob/acfce85bbb11284ba3b0538845ff88ff2e4428ea/apriltag_ros/launch/continuous_detection.launch#L5 to use the optical frame of your camera or publish a transformation from your root to `camera` manually to connect the kinematic trees.

I have PR #101 pending that sets this automatically from the image header. Then you don't have to configure this anymore.
